### PR TITLE
Added dynamic passing of AudioEncoding, OutputFormat and AudioEncodingBitRate

### PR DESCRIPTION
**Pull request by RakanNimer**
Options passed to and used by prepareRecordingPath on android are : 
`OutputFormat` (String) : `mpeg_4` `aac_adts` `amr_nb` `amr_wb` `three_gpp` `webm`
`AudioEncoding`(String) : `aac` `aac_eld` `amr_nb` `amr_wb` `he_aac` `vorbis`
`SampleRate` (int)
`Channels` (int)
`AudioEncodingBitRate` (int)

### CODE REVIEW

**Comment by jsierles** [comment]
What do you think about unifying the APIs here, then mapping the values to the correct native value in our library? I think this would be less hassle for authors.

**Comment by jsierles** [comment]
To be clear on the last message: support the same encoding values option names when they are supported by both platforms.

**Comment by RakanNimer** [comment]
Hey @jsierles, 

If I'm not mistaken I think this is already done : 

The AudioEncoding parameter in iOS supports : lpcm ima4 aac MAC3 MAC6 ulaw alaw mp1 mp2 alac
In android : aac aac_eld amr_nb amr_wb he_aac vorbis (which are all the [supported formats by android](https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html) )
The only type supported by both is aac and setting it from JS side in `recordingSettings['AudioEncoding']` as `'aac'` will work on both platforms. 

Is there something I'm missing ?

Cheers

**Comment by jsierles** [comment]
OK, thanks for the clarification there - looks good. Anything else need to be done?

**Comment by RakanNimer** [comment]
Not on this PR, but will be working on a new one to track recording progress soon !

**Pull request merged**
