### PR TITLE
Added checkAuthorizationStatus and requestAuthorization promise methods

### PR DESCRIPTION
**Pull request by wootwoot1234**
Added checkAuthorizationStatus promise method to check if app is authorized to use the microphone.  Returns a string with "undetermined", "granted" or "denied"

Added a requestAuthorization promise method that requests permission to use the microphone.  It returns true if granted and false if denied.

Here's an example of how to use the code:

        // checkAuthorizationStatus
        AudioRecorder.checkAuthorizationStatus()
        .then((result) => {
            switch(result) {
                case "undetermined":
                    // Recording permission has not been requested
                break;
                case "denied":
                    // Recording permission has been denied.  Explain to user that they
                    // need to go to settings and enable microphone access
                break;
                case "granted":
                    // Recording permission has been granted.
                break;
            }
        })
        .catch((err) => {
            console.error(err.message);
        });

        // requestAuthorization
        AudioRecorder.requestAuthorization()
        .then((granted) => {
            if(granted) {
                // User granted permission to use the microphone
            } else {
                // User did not give permission to use the microphone
            }
        });

### CODE REVIEW

**Comment by wootwoot1234** [comment]
Here is a example of how to use:

        AudioRecorder.checkDeviceAuthorizationStatus()
        .then((granted) => {
            if(granted) {
                // Authorized
            } else {
                // Not Authorized
            }
        })
        .catch((err) => {
            console.error(err.message);
        });

**Comment by jsierles** [comment]
:+1:

**Comment by Fatxx** [comment]
Can you please give some example how to enable recording? I could make this working on simulator but it's not working on device

**Comment by wootwoot1234** [comment]
@Fatxx check out the example code here:  https://github.com/jsierles/react-native-audio/tree/master/AudioExample

**Comment by squeirozmello** [comment]
@wootwoot1234, I am having the same problem as @Fatxx, I looked through the example but I didn't find out where do you ask for requestAuthorization

**Comment by Fatxx** [comment]
@wootwoot1234 thanks for you response but It doesn't seems to have any requestAuthorization logic in there.

**Comment by Fatxx** [comment]
I'm get in an error when I try to resolve the promise,

```ExceptionsManager.js:76 Exception 'The RCTPromiseResolveBlock must be the second to last parameter in -[AudioRecorderManager requestAuthorization:(RCTPromiseResolveBlock)resolve]' was thrown while invoking requestAuthorization on target AudioRecorderManager with params (
    4,
    5
)```

**Comment by wootwoot1234** [comment]
@squeirozmello, does the code below help?

@Fatxx, can you post your code?

This is what I'm using in my code:

    AudioRecorder.checkAuthorizationStatus()
    .then((result) => {
        switch(result) {
            case "undetermined":
                // Recording permission has not been requested
                AudioRecorder.requestAuthorization()
                .then((granted) => {
                    if(granted) {
                        // User granted permission to use the microphone
                        this.setState({
                            hasPermission: false
                        });
                        var title = "Need Access to Microphone";
                        var message = 'To enable access click the Settings button below and enable the microphone.';
                        this.openPrompt(
                            title,
                            message,
                            ()=>{
                                this.closePrompt();
                                this.goToSettings();
                            },
                            this.closePrompt.bind(this),
                            "Settings",
                        );
                    } else {
                        // User did not give permission to use the microphone
                        this.setState({
                            hasPermission: true
                        });
                        // Ok, permission was granted, set hasPermission and call record audio again.
                        this.recordAudio();
                    }
                });
            break;
            case "denied":
                // Recording permission has been denied.  Explain to user that they
                // need to go to settings and enable microphone access
                this.setState({
                    hasPermission: false
                });
                var title = "Need Access to Microphone";
                var message = 'To enable access click the Settings button below and enable the microphone.';
                this.openPrompt(
                    title,
                    message,
                    ()=>{
                        this.closePrompt();
                        this.goToSettings();
                    },
                    this.closePrompt.bind(this),
                    "Settings",
                );
            break;
            case "granted":
                // Recording permission has been granted.
                this.setState({
                    hasPermission: true
                });
                // Ok, permission was granted, set hasPermission and call record audio again.
                this.recordAudio();
            break;
        }
    })
    .catch((err) => {
        console.error(err.message);
    });

**Comment by wootwoot1234** [comment]
@Fatxx if it's working on the simulator but not on the device check if the microphone is enabled for your app in the "Settings" app on your device.

**Comment by Fatxx** [comment]
I only got 'Mobile Data' as an option om my app "Settings", do I need to add some key to plist?

**Comment by wootwoot1234** [comment]
I think it will show up in settings when you request permission to use the microphone (I might be wrong).  Looks like you haven't requested permission.  Post your code so I can see what you're doing.

**Comment by Fatxx** [comment]
```
class Jam extends Component {
    constructor(props) {
        super(props);

        shouldCreateJamDir();

        console.log('before')
        AudioRecorder.checkAuthorizationStatus()
        .then((result) => {
          console.log('result', result)
          debugger;
            switch(result) {
                case "undetermined":
                AudioRecorder.requestAuthorization()
                  .then((granted) => {
                    debugger;
                    if (granted) {
                        // User granted permission to use the microphone
                    } else {
                        // User did not give permission to use the microphone
                    }
                });
                  // Recording permission has not been requested
                break;
                case "denied":
                    // Recording permission has been denied.  Explain to user that they
                    // need to go to settings and enable microphone access
                break;
                case "granted":
                    // Recording permission has been granted.
                break;
            }
        })
        .catch((err) => {
            console.error(err.message);
        });

        this._handleSendTo = this._handleSendTo.bind(this);
        this._handleJamButtonPress = this._handleJamButtonPress.bind(this);
    }

    componentDidMount() {
        
        var record_audio_path = AudioUtils.LibraryDirectoryPath + '/test.caf';

        AudioRecorder.prepareRecordingAtPath(record_audio_path);

        AudioRecorder.onProgress = (audio) => {
            this.props.setJamState({duration: audio.currentTime.toFixed(2)});
        };

        AudioPlayer.onProgress = (audio) => {
            let currentTime = audio.currentTime;

            console.log('currentTime', currentTime);
            console.log('this.props.jam.duration', this.props.jam.duration);
        };

        AudioRecorder.onFinished = (data) => {
            this.props.setJamState({
                jam_file: record_audio_path,
                isReadyToShare: true,
                recording: false,
                playing: false
            });
        };
    }```

**Comment by Fatxx** [comment]
@wootwoot1234  The problem is that I don't have that in settings, so result returns 'denied' on device.

**Comment by Fatxx** [comment]
How you do to request permissions?

On Wednesday, 13 April 2016, Tom <notifications@github.com> wrote:

> I think it will show up in settings when you request permission to use the
> microphone (I might be wrong). Looks like you haven't requested permission.
> Post your code so I can see what you're doing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsierles/react-native-audio/pull/47#issuecomment-209155379>
>


-- 
Cumprimentos,
*André Fatia*

**Comment by wootwoot1234** [comment]
Sorry, I'm not sure what is going wrong with your code.  Have you tried just adding this code in the compnentDidMount() method?  Make sure you comment everything else out in all other methods.

    // requestAuthorization
    AudioRecorder.requestAuthorization()
    .then((granted) => {
        if(granted) {
            // User granted permission to use the microphone
        } else {
            // User did not give permission to use the microphone
        }
    });

**Comment by Fatxx** [comment]
Yes I did, throws an error. Can you supply your prompt component?

**Comment by wootwoot1234** [comment]
I'm not sure what is going on with your code but you need to post.  Please post the code you're testing and the errors you're getting.  Do you have another device you can test on?  You said it works on the simulator and not on the device?

**Comment by Fatxx** [comment]
I got this error when the application initialize with the code above: ```Exception 'The RCTPromiseResolveBlock must be the second to last parameter in -[AudioRecorderManager requestAuthorization:(RCTPromiseResolveBlock)resolve]' was thrown while invoking requestAuthorization on target AudioRecorderManager with params (
    6,
    7
)```  I just need to know how to trigger settings....

**Comment by Fatxx** [comment]
@wootwoot1234 Any ideas on this?

**Comment by wootwoot1234** [comment]
Please remember this is an open source project and I'm helping you because
I want to not because I need to. I'm pretty busy right now with my own
projects and can only help you if you answer all my questions.

On Apr 13, 2016, at 10:45 AM, André Luz Fatia <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

@wootwoot1234 <https://github.com/wootwoot1234> Any ideas on this?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/jsierles/react-native-audio/pull/47#issuecomment-209518647>

**Comment by Fatxx** [comment]
Sorry, I did test in 5s and 6s l

**Comment by Fatxx** [comment]
I was already in touch with 2 iOS developers and we can't get the alert to pop up, granted variable always return false

**Comment by wootwoot1234** [comment]
Try creating a new react native project, add this module and then in the
componentDidMount method, try to start a recording.  If that works, add in
parts of your project into the new project until it breaks and you'll know
where your problem is.  You shouldn't need to request access, you can just
start a recording and the app will request access on it's own.

If creating a new project doesn't work, post the error and the contents of
your index.ios.js file so I can see the code.

**Comment by Fatxx** [comment]
Thank you Tom we already created a new project and your module worked. So
it's probably our dependencies or settings that are breaking something.
Thanks anyway

On Wednesday, 13 April 2016, Tom <notifications@github.com> wrote:

> Try creating a new react native project, add this module and then in the
> componentDidMount method, try to start a recording. If that works, add in
> parts of your project into the new project until it breaks and you'll know
> where your problem is. You shouldn't need to request access, you can just
> start a recording and the app will request access on it's own.
>
> If creating a new project doesn't work, post the error and the contents of
> your index.ios.js file so I can see the code.
>
> On Wednesday, April 13, 2016, André Luz Fatia <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I was already in touch with 2 iOS developers and we can't get the alert
> to
> > pop up, granted variable always return false
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsierles/react-native-audio/pull/47#issuecomment-209645819
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsierles/react-native-audio/pull/47#issuecomment-209674373>
>


-- 
Cumprimentos,
*André Fatia*

**Comment by wootwoot1234** [comment]
When you figure out what was wrong, post your solution to this thread, it might help someone else. Good luck!

**Comment by squeirozmello** [comment]
@wootwoot1234 thank you very much for your help! That code helped me a lot! Best

**Comment by Fatxx** [comment]
It was probably this https://github.com/zmxv/react-native-sound library that was breaking this. So if someone have the same issue try to remove this one.

**Pull request merged**
