### PR TITLE
Support RN 0.47

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by luky1971** [comment]
Any reason we haven't merged this yet?

**Comment by aaronbuchanan** [comment]
29 days ago I came here and liked the comment above for a problem that's preventing me from using this lib. Any word on whether this is going to get merged in? I've checked several tickets :\

**Comment by ovr** [comment]
Btw, at @interpals We are using own fork of this library

@aaronbuchanan you can try to use it 

https://github.com/interpals/react-native-audio

**Comment by jsierles** [comment]
Sorry for the radio silence. Can someone rebase with master?

**Pull request closed without merging**
