### PR TITLE
Update AudioRecorderManager.m to include requiresMainQueueSetup

### PR DESCRIPTION
**Pull request by berkcoker**
This commit handles the yellow warning bubble that pops up at app restart.

### CODE REVIEW

**Comment by pistonsky** [comment]
Guys, can we merge this please?

**Comment by berkcoker** [comment]
@jsierles Can we merge this? This is a pretty straightforward edit.

**Comment by Arjanvanmaren** [comment]
Could this be merged?

**Comment by martinzuern** [comment]
What's blocking this PR from being merged?

**Comment by ariesjia** [comment]
pls merge this PR

**Comment by christian150590** [comment]
Could you please merge this PR?

**Pull request closed without merging**
