### PR TITLE
Audio finished not firing

### PR DESCRIPTION
**Pull request by hartmamt**
A few changes that were required to get the audio player to fire the finished playing event...

### CODE REVIEW

**Comment by hartmamt** [comment]
Done, sorry about that!

**Comment by hartmamt** [comment]
Can you publish to npm after you accept this? thanks!

**Comment by jsierles** [comment]
Sure thing - would you mind squashing commits?

**Comment by hartmamt** [comment]
I'm going to close and reopen this with one commit.

**Pull request closed without merging**
