### PR TITLE
Added Android support

### LINKED ISSUE #64: Android support?

### PR DESCRIPTION
**Pull request by RakanNimer**
Hey @jsierles,

Thanks for the great work on this module. 
I've mirrored your ios API on Android without many changes to the js module. (Fixes #64 #67 #45 )

The only thing that's missing is the progress tracking for recording and playing. For my use case, I'm handling it on the JS side, but can try to add it if people need it.

I made all function return promises to make it easier to handle errors and exceptions from JS. 

I can add promise support to the iOS version later if you don't mind, it shouldn't break any existing code, only allow people to do more with the current API. 

Cheers !

### CODE REVIEW

**Comment by jsierles** [comment]
This looks great! I'm just returning from vacation and will look at this over the next few days.

**Comment by jsierles** [comment]
I merged this, but noticed a few things that we should fix before releasing.

Format, bitrate and encoder are hard-coded to mp4, aac, and 32000. Can we pull these using the same options as the iOS, at least for formats that are supported?

**Comment by RakanNimer** [comment]
Yep, working on that now :)

**Comment by jsierles** [comment]
Great! I'm just updating the README a bit.

**Comment by jsierles** [comment]
Actually, I'll wait for your changes. I'd like to add a grid for iOS/android support of different options, like https://github.com/zmxv/react-native-sound

The eventual goal will be to merge this with that package. I wanted Android support first, so we're close now!

**Pull request merged**
