### PR TITLE
[Android] Add Timer

### PR DESCRIPTION
**Pull request by yleflour**
Added the timer feature on Android. The delay between each updates is 500ms. It might be a good idea to add this delay as a parameter in the config. The try/catch is uterly important as the timer thread might call a destroyed mediaPlayer object.

### CODE REVIEW

**Comment by yleflour** [comment]
@jsierles Here you go, 3 pull requests for the price of one 😉

**Comment by jsierles** [comment]
I'd love to merge this - could you rebase to master?

**Comment by yleflour** [comment]
@jsierles Seems like you removed AudioPlayerManager.java. Is it still worth it to try and merge the PR?

**Comment by jsierles** [comment]
Sorry about that. I felt the best decision would be to defer playback to more mature libraries. So, closing this one. Thanks for the submission!

**Comment by jsierles** [comment]
It would be useful to have progress reporting on Android if you're interested in that!

**Comment by yleflour** [comment]
@jsierles You might have kept playback a little longer and advised using react-native-sound. Until they implement the *Load sound from the network* feature I'm sticking with react-native-audio.

**Comment by jsierles** [comment]
Fair enough - however I don't use this library right now, and don't the support burden of playback, so won't be restoring it for future versions. I think submitting PRs to that library would be best!

**Pull request closed without merging**
