### PR TITLE
Use more ES6 features

### PR DESCRIPTION
**Pull request by calvinmikael**
Let me know if there are any issues.

### CODE REVIEW

**Comment by jsierles** [comment]
This conflicts with the latest update for looping audio. Could you fix and squash commits here?

**Comment by calvinmikael** [comment]
Updated it, let me know if there are any other issues, there is a bug in the pause functionality I'm trying to work through.

**Comment by jsierles** [comment]
Sorry for the delay - did you still want to merge this or submit another PR with more changes?

**Comment by calvinmikael** [comment]
You can merge if you want

**Comment by jsierles** [comment]
I can't reopen this PR since you deleted your fork.

**Comment by calvinmikael** [comment]
The fork was also deleted locally, the PR will have to come some other time.

**Pull request closed without merging**
