### PR TITLE
Added android files to package.json and added working example for android and iOS.

### PR DESCRIPTION
**Pull request by RakanNimer**
Tested on android and iOS. 👌

### CODE REVIEW

**Comment by jsierles** [comment]
Nice!

**Comment by jsierles** [comment]
I'm seeing this error. Maybe a gradle file is missing?

```
bichito:AudioExample joshua$ react-native run-android
Android project not found. Maybe run react-native android first?
```

**Comment by jsierles** [comment]
Looks like most of the gradle files are missing from the project, so the above command won't work. Should we add these, or instructions to generate them? I'm not sure how to do it with an existing project.

**Comment by RakanNimer** [comment]
Thanks for catching this : #92 should fix it :) Can you try it and let me know ?

**Pull request merged**
