### PR TITLE
Add Android support for playFromURL

### PR DESCRIPTION
**Pull request by neilsarkar**
Hi there, I noticed that playback on Android crashed due to playWithUrl being undefined. Looks like on Android the method is called playFromURL. This patch will allow playback on Android.

I didn't see a test harness or contribution guidelines so let me know if there are other steps you'd like me to take. Also I wasn't sure if Audio.ios.js was the right place to put Android stuff but that seemed to be the active code path.

### CODE REVIEW

**Comment by jsierles** [comment]
I think the best approach would be to unify the API method name, so change either the iOS or Android native method name. What do you think @RakanNimer ?

**Comment by RakanNimer** [comment]
Yep I agree with @jsierles, could you do that @neilsarkar ?

**Comment by RakanNimer** [comment]
LGTM :+1:

**Comment by jsierles** [comment]
Cool, this just needs to be rebased with master and we can merge.

**Comment by neilsarkar** [comment]
K, should be ready to go.

**Pull request merged**
