### PR TITLE
Add "base64" and "duration" for AudioRecorder.onFinished

### PR DESCRIPTION
**Pull request by q6112345**

### CODE REVIEW

**Comment by jsierles** [comment]
Closing this for now. Feel free to reopen if you'd like to discuss more. Thanks!

**Comment by stephanedemotte** [comment]
base64 could be very cool !

Why not merge ?

**Comment by n1ru4l** [comment]
@jsierles Any reason for not merging this? It is quite helpful and the API of react-native-camera and similar packages all have APIs that expose the base64 encoded file.

**Comment by jsierles** [comment]
What's the use case for returning base64?

**Comment by n1ru4l** [comment]
Uploading it as part of an post request as a form field for audio recognition

**Comment by jsierles** [comment]
This could also be handled using [react-native-fs](https://github.com/itinance/react-native-fs/blob/3e8b49e623f89333607ece6f6708cfc4dfa860b1/README.md#readfilefilepath-string-encoding-string-promisestring).

But my main concern is that large files can cause memory issues, and it makes more sense to submit large files directly from the native side rather than pass them over the bridge.

If someone wants to open a new PR that only addresses this case, and documents its limitations, I'd be happy to merge it.

**Comment by n1ru4l** [comment]
I can understand your concerns, however by comparing the small size of the recordings  and the corresponding relatively small performance overhead (in my use case) and implementing the upload on the native side for both platforms. Also I am not a huge fan of avoiding any additional native dependency (react-native-fs) where possible. 

I will follow with a pull request that adds a new boolean flag for including the base64 encoded image on the event object of `AudioRecorder.onFinished`. Since this will be an optional feature, there will be no performance issue for users already utilising react-native-audio.

For now I am only working on the iOS side of the application, therefore my first pull request will only implement the feature for iOS. I will try to follow with another PR when I am working on the android version. I hope that is okay for you @jsierles ?

**Pull request closed without merging**
